server:
  port: 8080

spring:
  application:
    name: gateway
  config:
    import:
      - optional:nacos:gateway.yaml
  cloud:
    nacos:
      config:
        server-addr: localhost:8848
      discovery:
        server-addr: localhost:8848
        namespace: public
        group: DEFAULT_GROUP
    gateway:
      routes:
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1
        - id: cart
          uri: lb://cart
          predicates:
            - Path=/api/cart/**
          filters:
            - StripPrefix=1
        - id: stock
          uri: lb://stock
          predicates:
            - Path=/api/stock/**
          filters:
            - StripPrefix=1
        - id: book
          uri: lb://book
          predicates:
            - Path=/api/books/**
          filters:
            - StripPrefix=1
        - id: order
          uri: lb://order
          predicates:
            - Path=/api/orders/**
          filters:
            - StripPrefix=1
        - id: payment
          uri: lb://payment
          predicates:
            - Path=/api/payment/**
          filters:
            - StripPrefix=1
        - id: ai
          uri: lb://ai-assistant
          predicates:
            - Path=/api/ai/**
          filters:
            - StripPrefix=1
      globalcors:
        # 全局跨域配置，解决前端浏览器跨域报错
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns:
              - "*" #允许所有前端域名访问
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*" #允许所有请求头
            allowCredentials: true
