server:
  port: 8051

spring:
  application:
    name: payment
  config:
    import:
      - optional:nacos:payment.yaml
  cloud:
    nacos:
      config:
        server-addr: localhost:8848
      discovery:
        server-addr: localhost:8848
        namespace: public
        group: DEFAULT_GROUP

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
