server:
  port: 8083

spring:
  application:
    name: cart
  config:
    import:
      - optional:nacos:cart.yaml
  cloud:
    nacos:
      config:
        server-addr: localhost:8848
      discovery:
        server-addr: localhost:8848
        namespace: public
        group: DEFAULT_GROUP

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
