server:
  port: 8050

spring:
  application:
    name: order
  config:
    import:
      - optional:nacos:order.yaml
  cloud:
    nacos:
      config:
        server-addr: localhost:8848
      discovery:
        server-addr: localhost:8848
        namespace: public
        group: DEFAULT_GROUP

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
